name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/share.png
    - assets/page-1/images/chevron-right.png
    - assets/page-1/images/rectangle-28-bg.png
    - assets/page-1/images/rectangle-27-bg.png
    - assets/page-1/images/rectangle-19-bg.png
    - assets/page-1/images/gg.png
    - assets/page-1/images/exterior.png
    - assets/page-1/images/share-JSk.png
    - assets/page-1/images/circled-up-left.png
    - assets/page-1/images/google.png
    - assets/page-1/images/slider.png
    - assets/page-1/images/share-vDE.png
    - assets/page-1/images/rectangle-19-bg-NoJ.png
    - assets/page-1/images/facebook.png
    - assets/page-1/images/chevron-right-RWg.png
    - assets/page-1/images/love.png
    - assets/page-1/images/wallet.png
    - assets/page-1/images/rectangle-42.png
    - assets/page-1/images/f28-b5f1-4db5-b053-45d3ff8ef488.png
    - assets/page-1/images/facebook-yiY.png
    - assets/page-1/images/share-8rL.png
    - assets/page-1/images/rectangle-19-bg-sWx.png
    - assets/page-1/images/ellipse-4-bg-xqe.png
    - assets/page-1/images/gg-swe.png
    - assets/page-1/images/pngwing-1.png
    - assets/page-1/images/mask-layer-xpx.png
    - assets/page-1/images/total-sales.png
    - assets/page-1/images/rectangle-25-bg-Uac.png
    - assets/page-1/images/wallet-GFz.png
    - assets/page-1/images/ellipse-4-bg.png
    - assets/page-1/images/ellipse-4-bg-miG.png
    - assets/page-1/images/exterior-hbv.png
    - assets/page-1/images/collapse-arrow.png
    - assets/page-1/images/nft-crypto-art-ideas.png
    - assets/page-1/images/coinbase-logo.png
    - assets/page-1/images/rectangle-19-bg-J8G.png
    - assets/page-1/images/share-c8x.png
    - assets/page-1/images/love-AAU.png
    - assets/page-1/images/love-hw6.png
    - assets/page-1/images/ellipse-4-bg-rJC.png
    - assets/page-1/images/love-Ccx.png
    - assets/page-1/images/love-ZCc.png
    - assets/page-1/images/circled-up-left-7V2.png
    - assets/page-1/images/share-5Rr.png
    - assets/page-1/images/customer.png
    - assets/page-1/images/slider-gRe.png
    - assets/page-1/images/love-3mz.png
    - assets/page-1/images/wallet-pGx.png
    - assets/page-1/images/metamask-logo.png
    - assets/page-1/images/wallet-Mng.png
    - assets/page-1/images/collapse-arrow-iNL.png
    - assets/page-1/images/gg-HAY.png
    - assets/page-1/images/mask-layer-qSx.png
    - assets/page-1/images/rectangle-41.png
    - assets/page-1/images/ellipse-4-bg-LuW.png
    - assets/page-1/images/love-uhi.png
    - assets/page-1/images/bada-club-xu-weili.png
    - assets/page-1/images/ellipse-4-bg-2nL.png
    - assets/page-1/images/collapse-arrow-aYx.png
    - assets/page-1/images/rectangle-19-bg-Mbe.png
    - assets/page-1/images/metamask-logo-K2g.png
    - assets/page-1/images/customer-Fh2.png
    - assets/page-1/images/chevron-right-oyS.png
    - assets/page-1/images/gg-mvG.png
    - assets/page-1/images/chevron-right-js6.png
    - assets/page-1/images/collapse-arrow-tjz.png
    - assets/page-1/images/customer-T2Q.png
    - assets/page-1/images/love-1Mz.png
    - assets/page-1/images/rectangle-42-9DJ.png
    - assets/page-1/images/rectangle-19-bg-HaQ.png
    - assets/page-1/images/love-SiC.png
    - assets/page-1/images/google-Q9E.png
    - assets/page-1/images/exterior-qvg.png
    - assets/page-1/images/rectangle-19-bg-CFS.png
    - assets/page-1/images/share-9gU.png
    - assets/page-1/images/share-7tC.png
    - assets/page-1/images/rectangle-19-bg-q7n.png
    - assets/page-1/images/mask-layer-PU4.png
    - assets/page-1/images/mask-layer-oAQ.png
    - assets/page-1/images/rectangle-24-bg.png
    - assets/page-1/images/mask-layer-8un.png
    - assets/page-1/images/ellipse-4-bg-xvk.png
    - assets/page-1/images/mask-layer-R68.png
    - assets/page-1/images/mask-layer-5Jx.png
    - assets/page-1/images/canvas.png
    - assets/page-1/images/mask-layer-8jS.png
    - assets/page-1/images/mask-layer-BzY.png
    - assets/page-1/images/mask-layer-3Wx.png
    - assets/page-1/images/mask-layer-yhr.png
    - assets/page-1/images/rectangle-27-bg-piU.png
    - assets/page-1/images/share-aBr.png
    - assets/page-1/images/coinbase-logo-ior.png
    - assets/page-1/images/rectangle-26-bg.png
    - assets/page-1/images/rectangle-28-bg-EGQ.png
    - assets/page-1/images/canvas-P9J.png
    - assets/page-1/images/mask-layer-Y2C.png
    - assets/page-1/images/rectangle-25-bg.png
    - assets/page-1/images/rectangle-41-bmA.png
    - assets/page-1/images/rectangle-19-bg-ZT6.png
    - assets/page-1/images/pngwing-2.png
    - assets/page-1/images/logout-rounded.png
    - assets/page-1/images/rectangle-22-bg.png
    - assets/page-1/images/ellipse-4-bg-QyW.png
    - assets/page-1/images/mask-layer-sEp.png
    - assets/page-1/images/ellipse-4-bg-nZv.png
    - assets/page-1/images/mask-layer.png
    - assets/page-1/images/rectangle-26-bg-YzL.png
    - assets/page-1/images/rectangle-21-bg.png
    - assets/page-1/images/customer-kSc.png
    - assets/page-1/images/rectangle-11-bg.png
    - assets/page-1/images/graph.png
    - assets/page-1/images/rectangle-24-bg-ti4.png
    - assets/page-1/images/ellipse-22-bg.png
    - assets/page-1/images/rectangle-61.png
    - assets/page-1/images/exterior-epg.png
    - assets/page-1/images/rectangle-22-bg-5Di.png
    - assets/page-1/images/rectangle-62.png
    - assets/page-1/images/logout-rounded-Hrg.png
    - assets/page-1/images/exterior-vwS.png
    - assets/page-1/images/rectangle-21-bg-TRa.png
    - assets/page-1/images/customer-uX6.png
    - assets/page-1/images/wallet-whr.png
    - assets/page-1/images/add-user-male.png
    - assets/page-1/images/rectangle-23-bg.png
    - assets/page-1/images/gg-hZJ.png
    - assets/page-1/images/rectangle-60.png
    - assets/page-1/images/rectangle-23-bg-Lkg.png
    - assets/page-1/images/gg-hyz.png
    - assets/page-1/images/rectangle-63.png
    - assets/page-1/images/customer-RU4.png
    - assets/page-1/images/gg-gGx.png
    - assets/page-1/images/gg-zRN.png
    - assets/page-1/images/wallet-W88.png
    - assets/page-1/images/customer-MLL.png
    - assets/page-1/images/gg-eRW.png
    - assets/page-1/images/exterior-APJ.png
    - assets/page-1/images/mask-layer-GYx.png
    - assets/page-1/images/exterior-gKa.png
    - assets/page-1/images/gg-7bW.png
    - assets/page-1/images/customer-teC.png
    - assets/page-1/images/wallet-4et.png
    - assets/page-1/images/customer-ppG.png
    - assets/page-1/images/exterior-1Qc.png
    - assets/page-1/images/wallet-SF2.png
    - assets/page-1/images/gg-8aC.png
    - assets/page-1/images/exterior-eDE.png
    - assets/page-1/images/wallet-3yS.png
    - assets/page-1/images/exterior-aFi.png
    - assets/page-1/images/customer-s7n.png
    - assets/page-1/images/customer-zoJ.png
    - assets/page-1/images/exterior-jwn.png
    - assets/page-1/images/wallet-AK2.png
    - assets/page-1/images/rectangle-51.png
    - assets/page-1/images/ellipse-18-bg.png
    - assets/page-1/images/ellipse-10-bg.png
    - assets/page-1/images/circled-up-left-FQC.png
    - assets/page-1/images/wallet-eFJ.png
    - assets/page-1/images/ellipse-20-bg.png
    - assets/page-1/images/ellipse-12-bg.png
    - assets/page-1/images/ellipse-8-bg.png
    - assets/page-1/images/ellipse-14-bg.png
    - assets/page-1/images/ellipse-16-bg.png
    - assets/page-1/images/ellipse-10-bg-4RW.png
    - assets/page-1/images/ellipse-8-bg-v5v.png
    - assets/page-1/images/ellipse-18-bg-ikG.png
    - assets/page-1/images/circled-up-left-pLG.png
    - assets/page-1/images/search.png
    - assets/page-1/images/ellipse-20-bg-gXr.png
    - assets/page-1/images/ellipse-12-bg-UH6.png
    - assets/page-1/images/search-xdN.png
    - assets/page-1/images/ellipse-16-bg-SYp.png
    - assets/page-1/images/ellipse-14-bg-yqa.png
    - assets/page-1/images/exterior-ULp.png
    - assets/page-1/images/customer-FRz.png
    - assets/page-1/images/gg-2uN.png
    - assets/page-1/images/wallet-ynx.png
    - assets/page-1/images/gg-NH6.png
    - assets/page-1/images/mastercard-logo-1.png
    - assets/page-1/images/rectangle-51-sjn.png
    - assets/page-1/images/customer-Vz8.png
    - assets/page-1/images/exterior-VVr.png
    - assets/page-1/images/wallet-mn8.png
    - assets/page-1/images/wallet-Duz.png
    - assets/page-1/images/customer-bHz.png
    - assets/page-1/images/gg-5Pv.png
    - assets/page-1/images/chevron-right-xRW.png
    - assets/page-1/images/exterior-Yvc.png
    - assets/page-1/images/chevron-right-m28.png
    - assets/page-1/images/mastercard-logo-1-cSc.png
    - assets/page-1/images/rectangle-42-bg.png
    - assets/page-1/images/rectangle-41-bg.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
